Support Python with UV (#107)

diff --git a/polyglot-release b/polyglot-release
--- a/polyglot-release
+++ b/polyglot-release
@@ -289,6 +289,16 @@ function is_monoglot_python() {
 }
 function pre_release_python() {
   check_for_tools "sed"
+  if [[ -f uv.lock && -f pyproject.toml ]]; then
+      if [[ -z $(python_uv_project_name) ]]; then
+        echo "This looks like a Python UV project, but the project name is blank or missing."
+        exit 1
+      fi
+      if [[ -z $(python_uv_revision) ]]; then
+        echo "This looks like a Python UV project, but the revision is blank or missing."
+        exit 1
+      fi
+  fi
 }
 function release_python() {
   if [[ -f pyproject.toml ]]; then
@@ -301,10 +311,40 @@ function release_python() {
     -e "s/\(version *= *\"\)[0-9]*\.[0-9]*\.[0-9]*\(\"\)/\1$NEW_VERSION\2/" \
     "$PROJECT_FILE"
   rm -f "$PROJECT_FILE.tmp"
+  
+  # Update version and revision in uv.file file
+  if [[ -f uv.lock && -f pyproject.toml ]]; then
+    # Find dependency entry for this project.
+    line=$(grep -n -m 1 "name *= *\"$(python_uv_project_name)\"" uv.lock | cut -d ":" -f1)
+    # Print everything that precedes the project entry
+    head -n "$line"  uv.lock > uv.lock.tmp
+    # Print the new version
+    echo "version = \"$NEW_VERSION\"" >> uv.lock.tmp
+    # Print everything after the version
+    tail -n "+$((line + 2))" uv.lock >>  uv.lock.tmp
+    # Replace the file.
+    mv uv.lock.tmp uv.lock
+    rm -f uv.lock.tmp
+    
+    sed -i".tmp" \
+        -e "s/\(revision *= *\)[0-9]*/\1$(python_uv_next_revision)/" \
+        uv.lock
+    rm -f uv.lock.tmp
+  fi
 }
 function post_release_python() {
   # noop
   :
+}
+function python_uv_project_name() {
+  grep -E  'name *= *"[a-z]+"' pyproject.toml  | sed 's/name *= *"//' | sed 's/"//'
+}
+function python_uv_next_revision() {
+  REVISION=$(python_uv_revision)
+  echo $((REVISION + 1))
+}
+function python_uv_revision() {
+  grep -E  'revision *= *[0-9]+' uv.lock  | sed 's/revision *= *//'
 }
 
 SUPPORTED_LANGUAGES+=("ruby")
