Check for missing GPG setup (#34)
* Add a way to check for missing tools

This is quite a major change for the tests. We're isolating them to only
have access to /bin and /usr/bin in the PATH, and everything else we add
as wrapper scripts in a $workdir/bin folder delegating to your local
install of the tool.

This allows us to remove the tool from $workdir/bin and create the
scenario where you don't have that tool installed.

We've also added the facility to start a manul test session in a
particular fixuture, with all the same git repos, isolated PATH setup
etc as you'd get in a test. To start a manual test session, pass the
path to the fixture to ./polyglot-release-test

* Add checks for user.signingkey and matching GPG key

* Update docs about running manual tests

* Helpful prompt on manual test session

* Don't bother tesing check_for_tool "gpg"

Not easy to test in CI

* Remove all the bin stubbing stuff

* Remove unneccesary env var

* It's exploratory testing

diff --git a/polyglot-release b/polyglot-release
--- a/polyglot-release
+++ b/polyglot-release
@@ -181,6 +181,24 @@ function check_in_git_root_directory() {
   fi
 }
 
+function check_gpg_keys_configured() {
+  if [[ -z $(git config user.signingkey) ]]; then
+    echo "You do not have a user.signingkey configured in git!"
+    echo
+    echo "All commits need to be signed. Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key"
+    exit 1
+  fi
+  if [[ ! $(gpg --list-secret-keys | grep $(git config user.signingkey)) ]]; then
+    echo "Your git user.signingkey ($(git config user.signingkey)) was not found in your GPG keys."
+    echo
+    echo "To see all your GPG keys, use:"
+    echo "    gpg --list-secret-keys"
+    echo
+    echo "All commits need to be signed. Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key"
+    exit 1
+  fi
+}
+
 function check_git_tags_fetched() {
   if [[ -z "$(git tag --list "v$(changelog latest)")" ]]; then
     echo "No git tag found for v$(changelog latest) (found in CHANGELOG.md)!"
@@ -260,9 +278,10 @@ done
 
 set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters
 
-check_for_tools "git" "changelog"
+check_for_tools "git" "changelog" "gpg"
 check_in_git_root_directory
 check_changelog_exists
+check_gpg_keys_configured
 check_git_tags_fetched
 check_git_index_clean
 
